language: node_js
node_js:
- '0.10'
notifications:
  email: false
deploy:
  provider: heroku
  app: heroku-badge2
  api-key: $HEROKU_API_KEY
  on:
    all_branches: true
before_deploy: if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
